default: &default
  adapter:  sqlite3
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: storage/development.sqlite3

test:
  <<: *default
  host: localhost
  database: storage/test.sqlite3

production:
  <<: *default
  database: storage/production.sqlite3
  username: crimethinc
  password: <%= ENV.fetch('PRODUCTION_DATABASE_PASSWORD', '') %>
  pool:     <%= ENV.fetch('DATABASE_CONNECTION_LIMIT') { 120 } %>
